### ISSUE TITLE
Dovecot

### ISSUE THREAD

**Issue by vansatchen** [Yar4e/lsmaildir#1]
Отличная утилита, спасибо!
Но для работы с директориями dovecot надо чуть модифицировать скрипт, т.к. утилита не показывает директории с точками(скрытые).
Для этого просто добавляем опцию -a
ls -a -1 "$@" > $lsofcurrentdir
ls -a -1 "$@" | sed -e 's:&:+:g' -e 's:,:/:g' -e 's:++:+-+:g' | iconv -f UTF7 -t UTF8 | paste - $lsofcurrentdir | column -s $'\t' -t

После этого можно видеть директории dovecot )

**Comment by Yar4e** [comment]
@vansatchen Рад, что вам она тоже пригодилась! Добавил опцию -A, чтобы выводить скрытые файлы, но при этом не выводить текущую и родительскую директории (. и ..).
